name: CI/CD Pipeline Loto Master

on:
  push:
    branches: [ "main" ]

jobs:
  # PHASE 1 : CONSTRUCTION & TESTS (Sur les serveurs de GitHub)
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: üì• R√©cup√©ration du code
        uses: actions/checkout@v3

      - name: ‚òï Installation de Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: üß™ Tests et Audit de Code (SonarCloud)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar

      - name: üîê Connexion √† Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: üèóÔ∏è Compilation et Envoi sur Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: tclrcc/loto-app:latest

  # PHASE 2 : DEPLOIEMENT (Sur votre VPS)
  deploy:
    needs: build-and-push # Ne se lance QUE si la phase 1 a r√©ussi
    runs-on: ubuntu-latest
    steps:
      - name: üöÄ Mise √† jour du VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/ubuntu/loto-analytics
            
            # 1. Mise √† jour du code source
            git fetch origin main
            
            # 2. NETTOYAGE S√âCURIS√â (Correction ici !)
            # On supprime tout SAUF le fichier .env qui contient tes secrets
            git clean -fd -e .env
            
            # 3. Reset pour √™tre synchro avec GitHub
            git reset --hard origin/main
            
            # 4. Mise √† jour des conteneurs
            docker compose pull loto_app
            docker compose up -d --remove-orphans
            
            # 5. Red√©marrage du proxy pour prendre en compte d'√©ventuels changements Caddyfile
            docker compose restart caddy
            
            # 6. NETTOYAGE DISQUE (Bonus Important)
            # Supprime les vieilles images Docker (celles d'avant le pull) pour ne pas saturer le disque du VPS
            docker image prune -f
