name: CI/CD Pipeline Loto Master

on:
  push:
    branches: [ "main" ]

jobs:
  # PHASE 1 : CONSTRUCTION & TESTS (Sur les serveurs de GitHub)
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ RÃ©cupÃ©ration du code
        uses: actions/checkout@v3

      - name: â˜• Installation de Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: ğŸ›¡ï¸ Lancement des Tests (SÃ©curitÃ©)
        run: mvn clean test
        # Si un test Ã©choue, le processus s'arrÃªte ici. Le site ne sera pas cassÃ©.

      - name: ğŸ” Connexion Ã  Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: ğŸ—ï¸ Compilation et Envoi sur Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: tclrcc/loto-app:latest

  # PHASE 2 : DEPLOIEMENT (Sur votre VPS)
  deploy:
    needs: build-and-push # Ne se lance QUE si la phase 1 a rÃ©ussi
    runs-on: ubuntu-latest
    steps:
      - name: ğŸš€ Mise Ã  jour du VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/ubuntu/loto-analytics
            # 1. On tÃ©lÃ©charge la nouvelle image toute prÃªte (ZÃ©ro compilation CPU)
            docker compose pull loto_app
            # 2. On redÃ©marre instantanÃ©ment
            docker compose up -d
