name: CI/CD Pipeline Loto Master

on:
  push:
    branches: [ "main" ]

jobs:
  # PHASE 1 : CONSTRUCTION & TESTS (Sur les serveurs de GitHub)
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: üì• R√©cup√©ration du code
        uses: actions/checkout@v3

      - name: ‚òï Installation de Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: üõ°Ô∏è Lancement des Tests (S√©curit√©)
        run: mvn clean test
        # Si un test √©choue, le processus s'arr√™te ici. Le site ne sera pas cass√©.

      - name: üîê Connexion √† Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: üèóÔ∏è Compilation et Envoi sur Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: tclrcc/loto-app:latest

  # PHASE 2 : DEPLOIEMENT (Sur votre VPS)
  deploy:
    needs: build-and-push # Ne se lance QUE si la phase 1 a r√©ussi
    runs-on: ubuntu-latest
    steps:
      - name: üöÄ Mise √† jour du VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/ubuntu/loto-analytics
            
            # 1. On t√©l√©charge les fichiers de configuration (Caddyfile, docker-compose)
            git pull origin main
            
            # 2. On t√©l√©charge la nouvelle image Java (Docker Hub)
            docker compose pull loto_app
            
            # 3. On red√©marre tout
            docker compose up -d
            
            # 4. On force Caddy √† relire son nouveau fichier de configuration
            docker compose restart caddy
